use `event-management`;

CREATE TABLE IF NOT EXISTS users (
	id INT AUTO_INCREMENT,
	username VARCHAR(30) NOT NULL,
	password VARCHAR(100) NOT NULL,
	CONSTRAINT PK_Users PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS profiles (
	id INT AUTO_INCREMENT,
	firstName VARCHAR(50) NOT NULL,
	lastName VARCHAR(50) NOT NULL,
	phone VARCHAR(15) NULL,
	userId INT NOT NULL,
	CONSTRAINT PK_Profiles PRIMARY KEY (id),
	CONSTRAINT FK_ProfilesUsers FOREIGN KEY (userId) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS images (
	id INT AUTO_INCREMENT,
	url VARCHAR(250) NOT NULL DEFAULT '/uploads/400x200.png',
	CONSTRAINT PK_Images PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events (
	id INT AUTO_INCREMENT,
	title VARCHAR(125) NOT NULL,
	startDate DATE NOT NULL,
	endDate DATE NOT NULL,
	location VARCHAR(150) NOT NULL,
	latitude VARCHAR(50) NOT NULL,
	longitude VARCHAR(50) NOT NULL,
	userId INT NOT NULL,
	imageId INT NOT NULL,
	CONSTRAINT PK_Events PRIMARY KEY (id),
	CONSTRAINT FK_EventsImages FOREIGN KEY (imageId) REFERENCES images(id),
	CONSTRAINT FK_EventsUsers FOREIGN KEY (userId) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS attendees (
	id INT AUTO_INCREMENT,
	date DATE NOT NULL,
	eventId INT NOT NULL,
	userId INT NOT NULL,
	CONSTRAINT PK_Attendees PRIMARY KEY (id),
	CONSTRAINT FK_AttendeesEvents FOREIGN KEY (eventId) REFERENCES events(id),
	CONSTRAINT FK_AttendeesUsers FOREIGN KEY (userId) REFERENCES users(id)
);
